import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Transition from "@/components/transitation";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "my portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Transition>{children}</Transition>
   
      </body>
    </html>
  );
}
